### ISSUE TITLE
Intergate TinyMCE plugin : code mirror

### ISSUE THREAD

**Issue by purplefish32** [claroline/CoreBundle#1038]
Any serious HTML work in TinyMCE HTML mode is a pain in the ass without syntax highlighting, auto-indenting and code linting, especially when you copy and paste old code.

There is a TinyMCE plugin that does all this here : http://www.avoid.org/codemirror-for-tinymce4/

I would suggest integrating it in all instances of TinyMCE

**Comment by ngodfraind** [comment]
Done on the 6.x-dev branch.
