### ISSUE TITLE
CreatePluginCommand problems

### ISSUE THREAD

**Issue by pitrackster** [claroline/CoreBundle#1055]
Hi !

It seems that there is a problem with this command :  (` php app/console claroline:plugin:create -i`)

- $vname (and probably $bname) variables are coming from nowhere. (used to be constructed like this : `$vname = strtolower($ivendor)` and `$bname = strtolower($ibundle) . -bundle `)

-  `$bundleManager = $this->container->get('claroline.manager.bundle_manager');` does not work but `$bundleManager = $this->getContainer()->get('claroline.manager.bundle_manager');` works.

- the created directory structure seems to be wrong. It is supposed to be `vendor/vendorname/bundlename-bundle/VendorName/BundleNameBundle` but the result is `vendor/Vendorname/BundleNameBundle`

Unless I missed something...

Thanks, Patrick

**Comment by ngodfraind** [comment]
I'll fix it asap.

**Comment by pitrackster** [comment]
thanks !

**Comment by ngodfraind** [comment]
It should be fixed now.

2015-03-10 11:47 GMT+01:00 Guillou Patrick <notifications@github.com>:

> thanks !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1055#issuecomment-78031131>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by pitrackster** [comment]
Perfect !
