### ISSUE TITLE
Installation via webinstaller - Postgres - column "widget_order" cannot be cast to type integer

### ISSUE THREAD

**Issue by rastafioul** [claroline/CoreBundle#1064]
Hi,
using apache2, php5, Postgres 9.1, and after having followed all requested changes from the webintaller I ran the installation. 
First, 
> <strong>it failed due to "maximum_execution_time" limited to 30 seconds. [Solved]</strong>
> changed it to 600
> restarted the server, 
> added a new database in postgres for this installation,
> restarted from SERVER/web/install.php, was pretty happy that everything was already written, 
> changed the database name on the requiered field 
> went on, crossing my fingers...

I then get
> <strong> SQL Error: </strong> 
>[ERROR] An exception has been thrown during installation
Message: An exception occurred while executing '
            ALTER TABLE claro_widget_home_tab_config ALTER widget_order TYPE INT
        ':
>SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "widget_order" cannot be cast to type integer</strong>

full log (not well seen with the code tag so here it is in plain text):

Clearing the cache...
Installing the platform from kernel...
[info] Checking database connection...
[info] Creating public sub-directories...
[info] Installing ClarolineCoreBundle...
[info] Launching pre-installation actions...
[info] Executing migrations...
[ERROR] An exception has been thrown during installation
Message: An exception occurred while executing '
            ALTER TABLE claro_widget_home_tab_config ALTER widget_order TYPE INT
        ':
SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "widget_order" cannot be cast to type integer
Trace: #0 /var/www/claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(702): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(PDOException), '\n            AL...', Array)
#1 /var/www/claroline/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php(271): Doctrine\DBAL\Connection->executeQuery('\n            AL...')
#2 /var/www/claroline/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(158): Doctrine\DBAL\Migrations\Version->execute('up', false, false)
#3 /var/www/claroline/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Migrator/Migrator.php(98): Doctrine\DBAL\Migrations\Migration->migrate(NULL)
#4 /var/www/claroline/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(166): Claroline\MigrationBundle\Migrator\Migrator->migrate(Object(Claroline\CoreBundle\ClarolineCoreBundle), 'farthest', 'up')
#5 /var/www/claroline/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(95): Claroline\MigrationBundle\Manager\Manager->doMigrate(Object(Claroline\CoreBundle\ClarolineCoreBundle), 'farthest', 'up')
#6 /var/www/claroline/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Manager/InstallationManager.php(75): Claroline\MigrationBundle\Manager\Manager->upgradeBundle(Object(Claroline\CoreBundle\ClarolineCoreBundle), 'farthest')
#7 /var/www/claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/PlatformInstaller.php(120): Claroline\InstallationBundle\Manager\InstallationManager->install(Object(Claroline\CoreBundle\ClarolineCoreBundle), true)
#8 /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(119): Claroline\CoreBundle\Library\Installation\PlatformInstaller->installFromKernel(false)
#9 /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(63): Claroline\WebInstaller\Installer->launchInstaller(Object(appProdProjectContainer), Object(Symfony\Component\Console\Output\StreamOutput))
#10 /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Controller.php(251): Claroline\WebInstaller\Installer->install()
#11 /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Kernel.php(64): Claroline\WebInstaller\Controller->installSubmitStep()
#12 /var/www/claroline/web/install.php(13): Claroline\WebInstaller\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}

**Comment by ngodfraind** [comment]
This is a well known problem. For now we only support mysql/mariadb. We
hoped that doctrine would help us doing more but has it turns out, it
causes many problems with other databases if we don't actively support them.

2015-03-20 10:01 GMT+01:00 rastafioul <notifications@github.com>:

> Hi,
> using apache2, php5, Postgres 9.1, and after having followed all requested
> changes from the webintaller I ran the installation.
> First,
>
> *it failed due to "maximum_execution_time" limited to 30 seconds. [Solved]*
> changed it to 600
> restarted the server,
> added a new database in postgres for this installation,
> restarted from SERVER/web/install.php, was pretty happy that everything
> was already written,
> changed the database name on the requiered field
> went on, crossing my fingers...
>
> I then get
>
> * SQL Error: *
> [ERROR] An exception has been thrown during installation
> Message: An exception occurred while executing '
> ALTER TABLE claro_widget_home_tab_config ALTER widget_order TYPE INT
> ':
> SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "widget_order" cannot
> be cast to type integer
>
> full log (not well seen with the code tag so here it is in plain text):
>
> Clearing the cache...
> Installing the platform from kernel...
> [info] Checking database connection...
> [info] Creating public sub-directories...
> [info] Installing ClarolineCoreBundle...
> [info] Launching pre-installation actions...
> [info] Executing migrations...
> [ERROR] An exception has been thrown during installation
> Message: An exception occurred while executing '
> ALTER TABLE claro_widget_home_tab_config ALTER widget_order TYPE INT
> ':
> SQLSTATE[42804]: Datatype mismatch: 7 ERROR: column "widget_order" cannot
> be cast to type integer
> Trace: #0
> /var/www/claroline/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(702):
> Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(PDOException),
> '\n AL...', Array)
> #1 <https://github.com/claroline/CoreBundle/pull/1>
> /var/www/claroline/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Version.php(271):
> Doctrine\DBAL\Connection->executeQuery('\n AL...')
> #2 <https://github.com/claroline/CoreBundle/pull/2>
> /var/www/claroline/vendor/doctrine/migrations/lib/Doctrine/DBAL/Migrations/Migration.php(158):
> Doctrine\DBAL\Migrations\Version->execute('up', false, false)
> #3 <https://github.com/claroline/CoreBundle/pull/3>
> /var/www/claroline/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Migrator/Migrator.php(98):
> Doctrine\DBAL\Migrations\Migration->migrate(NULL)
> #4 <https://github.com/claroline/CoreBundle/pull/4>
> /var/www/claroline/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(166):
> Claroline\MigrationBundle\Migrator\Migrator->migrate(Object(Claroline\CoreBundle\ClarolineCoreBundle),
> 'farthest', 'up')
> #5 <https://github.com/claroline/CoreBundle/pull/5>
> /var/www/claroline/vendor/claroline/migration-bundle/Claroline/MigrationBundle/Manager/Manager.php(95):
> Claroline\MigrationBundle\Manager\Manager->doMigrate(Object(Claroline\CoreBundle\ClarolineCoreBundle),
> 'farthest', 'up')
> #6 <https://github.com/claroline/CoreBundle/pull/6>
> /var/www/claroline/vendor/claroline/installation-bundle/Claroline/InstallationBundle/Manager/InstallationManager.php(75):
> Claroline\MigrationBundle\Manager\Manager->upgradeBundle(Object(Claroline\CoreBundle\ClarolineCoreBundle),
> 'farthest')
> #7 <https://github.com/claroline/CoreBundle/pull/7>
> /var/www/claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Installation/PlatformInstaller.php(120):
> Claroline\InstallationBundle\Manager\InstallationManager->install(Object(Claroline\CoreBundle\ClarolineCoreBundle),
> true)
> #8 <https://github.com/claroline/CoreBundle/pull/8>
> /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(119):
> Claroline\CoreBundle\Library\Installation\PlatformInstaller->installFromKernel(false)
> #9 <https://github.com/claroline/CoreBundle/pull/9>
> /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Installer.php(63):
> Claroline\WebInstaller\Installer->launchInstaller(Object(appProdProjectContainer),
> Object(Symfony\Component\Console\Output\StreamOutput))
> #10 <https://github.com/claroline/CoreBundle/pull/10>
> /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Controller.php(251):
> Claroline\WebInstaller\Installer->install()
> #11 <https://github.com/claroline/CoreBundle/pull/11>
> /var/www/claroline/vendor/claroline/web-installer/lib/Claroline/WebInstaller/Kernel.php(64):
> Claroline\WebInstaller\Controller->installSubmitStep()
> #12 <https://github.com/claroline/CoreBundle/pull/12>
> /var/www/claroline/web/install.php(13):
> Claroline\WebInstaller\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
> #13 <https://github.com/claroline/CoreBundle/pull/13> {main}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1064>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by rastafioul** [comment]
Thanks for such a quick answer,
I did not find anything on this problem therefore I opened this issue.
Thanks for the great job you are doing, guys!
