### ISSUE TITLE
Error when creating user through console

### ISSUE THREAD

**Issue by eldoniel** [claroline/CoreBundle#1208]
No error during install but a problem when creating user

After a fresh install through the install script we get this :
 ```[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                   
  Catchable Fatal Error: Argument 2 passed to Claroline\CoreBundle\Manager\TransfertManager::setImporters() must be of the type array, null given, called in  
   /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php on line 180 and defined ```

Quite the same problem after a classic install : 
``` PHP Notice:  Undefined property: Claroline\CoreBundle\Library\Workspace\Configuration::$data in /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Workspace/Configuration.php on line 173```

```PHP Catchable fatal error:  Argument 2 passed to Claroline\CoreBundle\Manager\TransfertManager::setImporters() must be of the type array, null given, called in /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php on line 180 and defined in /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php on line 337```

**Comment by ngodfraind** [comment]
I think I remember why it doesn't work. The update is supposed to take care
of that but if it didn't you can solve it that way:

- mv templates files/templates

(move this directory into the files folder).

chmod -R 0777 fiiles

And try again.

2015-05-22 13:52 GMT+02:00 Nicolas Dufour <notifications@github.com>:

> No error during install but a problem when creating user
>
> After a fresh install through the install script we get this :
>  [Symfony\Component\Debug\Exception\ContextErrorException]
> Catchable Fatal Error: Argument 2 passed to
> Claroline\CoreBundle\Manager\TransfertManager::setImporters() must be of
> the type array, null given, called in
> /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php
> on line 180 and defined
>
> Quite the same problem after a classic install :
> PHP Notice: Undefined property:
> Claroline\CoreBundle\Library\Workspace\Configuration::$data in
> /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Library/Workspace/Configuration.php
> on line 173
>
> PHP Catchable fatal error: Argument 2 passed to
> Claroline\CoreBundle\Manager\TransfertManager::setImporters() must be of
> the type array, null given, called in
> /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php
> on line 180 and defined in
> /var/www/Claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/TransfertManager.php
> on line 337
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1208>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by eldoniel** [comment]
It was already like that, I just checked. But it still doesn't work.

**Comment by ngodfraind** [comment]
Is there still something in your templates directory ?

2015-05-22 14:02 GMT+02:00 Nicolas Dufour <notifications@github.com>:

> It was already like that, I just checked. But it still doesn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1208#issuecomment-104644321>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
If it still doesn't work, you can try.
Then chmod the folder.
cp vendor/claroline/core-bundle/.../Resources/template/default.zip
files/templates/default.zip

2015-05-22 14:16 GMT+02:00 Godfraind Nicolas <nicolas.godfraind@gmail.com>:

> Is there still something in your templates directory ?
>
> 2015-05-22 14:02 GMT+02:00 Nicolas Dufour <notifications@github.com>:
>
>> It was already like that, I just checked. But it still doesn't work.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/claroline/CoreBundle/issues/1208#issuecomment-104644321>
>> .
>>
>
>
>
> --
> Godfraind Nicolas
> 5, rue de la Carrière
> 6592 Monceau-Imbrechies
> GSM: 0472 94 80 99
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by eldoniel** [comment]
I just did that, it works. default.zip was missing indeed.
Thank you!
