### ISSUE TITLE
Error on activity listener open action

### ISSUE THREAD

**Issue by maxailloud** [claroline/CoreBundle#1223]
On an installed server I got this error in the log:

 > Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Claroline\CoreBundle\Manager\ActivityManager::getEvaluationByUserAndActivityParams() must be an instance of Claroline\CoreBundle\Entity\User, string given, called in /data/www/clarolineconnect/claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Listener/Resource/ActivityListener.php on line 169 and defined" at /data/www/clarolineconnect/claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/ActivityManager.php line 665 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to Claroline\\CoreBundle\\Manager\\ActivityManager::getEvaluationByUserAndActivityParams() must be an instance of Claroline\\CoreBundle\\Entity\\User, string given, called in /data/www/clarolineconnect/claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Listener/Resource/ActivityListener.php on line 169 and defined at /data/www/clarolineconnect/claroline/vendor/claroline/core-bundle/Claroline/CoreBundle/Manager/ActivityManager.php:665)"}

**Comment by ngodfraind** [comment]
Activities cannot be opened by anonymous people. I'll throw an AccessDenied.
