### ISSUE TITLE
claroline:user:create Command force sets fake email

### ISSUE THREAD

**Issue by ChMat** [claroline/CoreBundle#1252]
Hi,

I'm looking for the simplest way to create new users from another tool. I found the `claroline:user:create` command but this command forces a fake email address.

Do you know the reason for this?

Thanks for your insight!

**Comment by ngodfraind** [comment]
The email adress is a required field and this command doesn't ask for a valid adress (it's mainly used as a dev command). That's why a fake email is created when it is used.

**Comment by ngodfraind** [comment]
The command has been update and now asks for the user email
Claroline/CoreBundle@f799111d34d989b44de1752daeb9f69542183c26
