### ISSUE TITLE
error with claroline:create:user

### ISSUE THREAD

**Issue by stmolivier** [claroline/CoreBundle#1277]
i'm installing a clean 5.1.11.7 version, and after the curl script i did a claroline:install that went well. But when afterwards i try : php app/console claroline:create:user -a
i have : 
```
 [Doctrine\ORM\ORMInvalidArgumentException]                                                                                                        
  A new entity was found through the relationship 'Claroline\CoreBundle\Entity\Workspace\Workspace#creator' that was not configured to cascade per  
  sist operations for entity: Claroline\CoreBundle\Entity\User@000000003130eb4200000000040e90dd. To solve this issue: Either explicitly call Entit  
  yManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"pers  
  ist"}). If you cannot find out which entity causes the problem implement 'Claroline\CoreBundle\Entity\User#__toString()' to get a clue.
```

and the user is not created

**Comment by ngodfraind** [comment]
Yes I broke something this afternoon. I'm on it.

2015-08-20 22:18 GMT+02:00 stmolivier <notifications@github.com>:

> i'm installing a clean 5.1.11.7 version, and after the curl script i did a
> claroline:install that went well. But when afterwards i try : php
> app/console claroline:create:user -a
> i have :
>
>  [Doctrine\ORM\ORMInvalidArgumentException]
>   A new entity was found through the relationship 'Claroline\CoreBundle\Entity\Workspace\Workspace#creator' that was not configured to cascade per
>   sist operations for entity: Claroline\CoreBundle\Entity\User@000000003130eb4200000000040e90dd. To solve this issue: Either explicitly call Entit
>   yManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"pers
>   ist"}). If you cannot find out which entity causes the problem implement 'Claroline\CoreBundle\Entity\User#__toString()' to get a clue.
>
> and the user is not created
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1277>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
This is now fixed.
