### ISSUE TITLE
Non published resources are visible when using impersonation

### ISSUE THREAD

**Issue by stefk** [claroline/CoreBundle#1305]
When "See as collaborator" is on, unpublished resources are visible and throw 403s when accessed.

**Comment by ngodfraind** [comment]
I could reproduce it. It's going to be fixed asap.

**Comment by ngodfraind** [comment]
The 403 error is not expected but the resource should still be visible because even as a collaborator, you're probably still the owner of the resource.

The "view as" function only changes the user roles and not the user itself.

**Comment by ngodfraind** [comment]
Fixed by Claroline/CoreBundle@1932692a5364a2ba8a30911216249d2c40486dc9
