### ISSUE TITLE
Les ressources ne s'affichent pas

### ISSUE THREAD

**Issue by ericvincenterv** [claroline/CoreBundle#1308]
Un administrateur/enseignant créé une formation avec inscription publique et il y intègre des ressources, comme par exemple un parcours. Il voit les ressources créées.

Un utilisateur/élève s'auto-inscrit à cette formation. Mais les ressources ne sont pas visibles par lui.

Ce dysfonctionnement n'apparaît pas dans la version v5.1.7 mais dans les versions suivantes (v5.1.11.15).

Après visualisation du code généré, nous avons constaté une erreur JS au niveau du resource_manager dans la variable PreFetchDirectory. 

Voir images.

![avant](https://cloud.githubusercontent.com/assets/5363344/9677714/9f46f88c-52dd-11e5-8063-0da34d0b9f74.png)

![apres](https://cloud.githubusercontent.com/assets/5363344/9677715/a14e3cda-52dd-11e5-95b5-e01d21277795.png)

**Comment by Elorfin** [comment]
When the User has not the rights to open resources, the call (in CoreBundle/Resources/views/Tool/workspace/resource_manager/resources.html.twig line 37) to : 

```
"preFetchedDirectory":  {{ render(controller('ClarolineCoreBundle:Resource:openDirectory', { 'nodeId': directoryId}))|raw }}
```

throws an exception :

```
<p>L'action open n'a pas pu être exécutée sur la resource 'Test inscription publique': accès refusé.</p> 
```

So the JavaScript object is not correctly initialized.

**Comment by ngodfraind** [comment]
That was fixed.
