### ISSUE TITLE
Date controlled resources are visible when using impersonation

### ISSUE THREAD

**Issue by stefk** [claroline/CoreBundle#1309]
Similar to #1305. Resources which are not accessible at some date shouldn't be visible when using "See as collaborator".

**Comment by ngodfraind** [comment]
It's the same as the other one. When using the impersonation, we replace the role of the current user.
He's still the owner of the resources so they're still visible... I've no idea on how to change this behaviour properly.

**Comment by stefk** [comment]
Yes, it's not a bug per se, just a strange behaviour for the user. 403's on the other hand aren't expected in the current implementation.

**Comment by ngodfraind** [comment]
Fixed by Claroline/CoreBundle@1932692a5364a2ba8a30911216249d2c40486dc9 aswell.
