### ISSUE TITLE
[Enhancement] Datetime access control on resources

### ISSUE THREAD

**Issue by stefk** [claroline/CoreBundle#1314]
* the current date picker should be replaced by a full datetime picker, in order to be able to specify precise hours instead of default 00h00:00

* resources not accessible due to time constraints should have an altered/greyed thumbnail just like unpublished ones.

**Comment by ngodfraind** [comment]
I agree. I'll try to do it after I release the 5.1.12.

**Comment by ngodfraind** [comment]
Done.
