### ISSUE TITLE
 Bug if I add a collecticiel without name

### ISSUE THREAD

**Issue by ericvincenterv** [claroline/CoreBundle#1319]
I want to add a "Collecticiel".

When I add a "Collecticiel" without name, ...

![collecticiel-vide](https://cloud.githubusercontent.com/assets/5363344/9736898/32c5ce62-5644-11e5-95d1-8d510de803fa.png)

..., I have his bug : 

![collecticiel-vide-2](https://cloud.githubusercontent.com/assets/5363344/9736902/3693c300-5644-11e5-9b40-e464a1ec22cd.png)

**Comment by ngodfraind** [comment]
A resource needs a name. If you're using the default form it's a bug
because it should returns the form with errors. Otherwise it's working as
expected.

2015-09-08 16:12 GMT+02:00 Eric VINCENT <notifications@github.com>:

> I want to add a "Collecticiel".
>
> When I add a "Collecticiel" without name, ...
>
> [image: collecticiel-vide]
> <https://cloud.githubusercontent.com/assets/5363344/9736898/32c5ce62-5644-11e5-95d1-8d510de803fa.png>
>
> ..., I have his bug :
>
> [image: collecticiel-vide-2]
> <https://cloud.githubusercontent.com/assets/5363344/9736902/3693c300-5644-11e5-9b40-e464a1ec22cd.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1319>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ericvincenterv** [comment]
I use the default form.

If I add a "text", I don't have this bug.

![texte](https://cloud.githubusercontent.com/assets/5363344/9737269/14ebd524-5646-11e5-931e-7c4121e63da8.png)

**Comment by ngodfraind** [comment]
Because I don't know wich form you're using, I'm assuming it's ResourceNameType and I just fixed it on the 5.x-stable.

**Comment by ericvincenterv** [comment]
With Claroline (v5.1.11.24), I have always the same result : 

![nom-vide](https://cloud.githubusercontent.com/assets/5363344/9993117/519be344-6076-11e5-8e30-d667bff24c6c.png)

**Comment by ngodfraind** [comment]
I looked at your code and I think I know where this come from. It's not from the CoreBundle.
You have a "DropZoneListener" (why is he named like this ?) that has the listenener for the 'create_form_innova_collecticiel'.
You use the 'DropZoneType' form. That form has no name validation and comes from the DropZone bundle.

**Comment by ericvincenterv** [comment]
Many thanks for help. I will modify for the next release.
