### ISSUE TITLE
Message: User A can see messages that user B sent to user C

### ISSUE THREAD

**Issue by ChMat** [claroline/CoreBundle#1355]
Hi,

I was notified about a strange behaviour in Claroline v5.1.11.16, that I was not able to reproduce.

Subject says it all, but you can see a few screenshots (descriptions in French) in this pdf: https://www.dropbox.com/s/i8r9bf3sejrm9an/Probl%C3%A8me%20de%20messagerie%20Ebac%20Connect.pdf?dl=0

Did anyone experience that same situation?

Thanks for your feedback!

**Comment by ngodfraind** [comment]
Ok, this is weird. I'll look at this. The dql request is probably wrong (I don't see anything else that would cause this behaviour).

**Comment by ngodfraind** [comment]
I was able to reproduce.
It happens when a message is sent to multiple users and they start to answer to each others.

I'm looking at it.

**Comment by ngodfraind** [comment]
This will be fixed in the next release of the message bundle
Claroline/MessageBundle@2ad638c2649137732bc85d198e91ef1ddcdd7219
