### ISSUE TITLE
No notification for the owner of a WS when a user registers and needs confirmation.

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/CoreBundle#1359]
All in the title. I've created a WS with open registration and checked the registration validation checkbox.
When a user clicks on register for this WS, he's in pending mode which is ok. But the owner of the ws has to go in his userlist for this WS and  click on the Pendig tab to see a user is waiting. This is not straightforward at all.

There should be a **notification for the owner asking him to go check**. Otherwise he might at some point forget to register some user when the course begins.
This is a necessary improvement i think.

Thank you

**Comment by ngodfraind** [comment]
I agree. It's going to have to wait a little bit but that's a very good point.

**Comment by CPASimUSante** [comment]
no problem. Thank you

**Comment by ngodfraind** [comment]
How do you want to receive the notifications ? as a message, a notification or an email. This shouldn't require a lot of dev so I can add it pretty quickly if we know what we want.

**Comment by CPASimUSante** [comment]
Since the user has a notification when his request to register is granted by the owner, i think it would be at least fair to do the same for the other way around : a notification.
If there is a message, i wouldn't be horrified either. Since the messages remains until they have been read maybe i would prefer a message though for this important information for the workspace creator who has tons of notifications (if forgets to turns them off :)) that he would not read all.
But you do as you see fit.

**Comment by ngodfraind** [comment]
I made a new issue for notifications. See Claroline/CoreBundle#1403
