### ISSUE TITLE
inconsistency for  ressource delete

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/CoreBundle#1363]
If i delete a resource by checking the checkbox and clicking on the trash icon, i have a alert saying i'm about to delete.
But if i delete the ressource using the dropdown menu under the icon and using delete option, i don't have an alert. It would be nice if there was an alert there too.

**Comment by ngodfraind** [comment]
I agree. This is something I plan to do 'soon'.

**Comment by ngodfraind** [comment]
Done. This will be improved later for path and resource that requires additional delete informations.
