### ISSUE TITLE
Bug for upload in tinyMCE

### ISSUE THREAD

**Issue by ericvincenterv** [claroline/CoreBundle#1364]
I want to upload a file with TinyMCE.

I have this problem.

![upload-bug-1](https://cloud.githubusercontent.com/assets/5363344/9992861/e05c562e-6074-11e5-9684-c16cfd9a91e2.png)

and I have this result : 

![upload-bug-2](https://cloud.githubusercontent.com/assets/5363344/9992862/e4c84bc8-6074-11e5-9afd-44cc4a74dcef.png)

In my localhost, I have this result after the upload : 
![upload-bug-3](https://cloud.githubusercontent.com/assets/5363344/9992922/4215dd36-6075-11e5-85b0-4dd2bc0acd97.png)

It's in DropZoneBundle and in CollecticielBundle.

**Comment by ngodfraind** [comment]
Fixed by Claroline/CoreBundle@56cca818d913138ea53e13b42a8baf99d287c739
