### ISSUE TITLE
bug for drag and drop in ressource management in desktop mode

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/CoreBundle#1367]
This seems to happen only in non-workspace mode = on desktop mode : i open the resource management and go to a WS folder. There, i can't drag/drop the resources. 
But If there i open a resource and do back in the browser this work.
If i am in a WS, i can do the drang and drop.

I've tested it in v6.3.8

**Comment by ngodfraind** [comment]
In the current build, users cannot add resource at the desktop root (everything is greyed) and that's why the upload fails.

**Comment by ngodfraind** [comment]
A warning is now shown before uploading the resource.
Claroline/CoreBundle@23386fd2668718d4ebabf64a7bd734aad5fd7998
