### ISSUE TITLE
Translation to be fixed in resources parameters

### ISSUE THREAD

**Issue by CPASimUSante** [claroline/CoreBundle#1374]
In a WS > parameters > Resources. In the advanced/ user tab 
workspaces/tool/properties/2/tool/3/config

there is twice "Editer" (in french), instead of Editer, Administrer

**Comment by ngodfraind** [comment]
This bug come from the InnovaPathBundle (they override the administrate translation key...).
I already reported it. Feel free to ask them too because it's not something I can change easily in the CoreBundle. 
The translation key is located in the translations/resources.xx.yml file.

**Comment by Elorfin** [comment]
I have changed the translation key for the administrate link. It should fix the it.

v5.3.9 or v6.0.4

**Comment by ngodfraind** [comment]
Thanks
