### ISSUE TITLE
Deleted users are still visible

### ISSUE THREAD

**Issue by ChMat** [claroline/CoreBundle#1377]
Hi,

It looks like deleted users through `CoreBundle/Manager/UserManager:deleteUser()` function are still visible in the admin interface. Is this a deliberate choice?

![deleted_users_visible](https://cloud.githubusercontent.com/assets/1511740/10058865/fe8ba0f8-6247-11e5-8a94-e114b0b9cf0c.png)

**Comment by ngodfraind** [comment]
This is not normal. Wich version are you using ?

2015-09-23 23:11 GMT+02:00 Christian <notifications@github.com>:

> Hi,
>
> It looks like deleted users through
> CoreBundle/Manager/UserManager:deleteUser() function are still visible in
> the admin interface. Is this a deliberate choice?
>
> [image: deleted_users_visible]
> <https://cloud.githubusercontent.com/assets/1511740/10058865/fe8ba0f8-6247-11e5-8a94-e114b0b9cf0c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1377>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ChMat** [comment]
According to my `composer.lock`, it's v5.1.11.27. But the footer keeps displaying v5.1.11.16.

**Comment by ngodfraind** [comment]
composer.lock is always right. The other one is the version stored in the
database. It's updated during the claroline:update command.

2015-09-23 23:26 GMT+02:00 Christian <notifications@github.com>:

> According to my composer.lock, it's v5.1.11.27. But the footer keeps
> displaying v5.1.11.16.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/CoreBundle/issues/1377#issuecomment-142734513>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ngodfraind** [comment]
I'm not able to reproduce it. Maybe the users weren't properly removed.
Here is a clue: is the user 'is_enabled' set to true in the database ?

If yes, how were they removed in the first place ? I'm not able to
reproduce this problem.
If you remove them again, do they still appear in the list ?

2015-09-23 23:32 GMT+02:00 Godfraind Nicolas <nicolas.godfraind@gmail.com>:

> composer.lock is always right. The other one is the version stored in the
> database. It's updated during the claroline:update command.
>
> 2015-09-23 23:26 GMT+02:00 Christian <notifications@github.com>:
>
>> According to my composer.lock, it's v5.1.11.27. But the footer keeps
>> displaying v5.1.11.16.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/claroline/CoreBundle/issues/1377#issuecomment-142734513>
>> .
>>
>
>
>
> --
> Godfraind Nicolas
> 5, rue de la Carrière
> 6592 Monceau-Imbrechies
> GSM: 0472 94 80 99
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by ChMat** [comment]
That's what I thought too. I have reproduced the `deleteUser()` function in a custom controller and the codebase is the same, except for the first lines in the function:

        if ($this->container->get('security.token_storage')->getToken()->getUser()->getId() === $user->getId()) {
            throw new \Exception('A user cannot delete himself');
        }

These are not in my action as I use an API token to authenticate the bot carrying the action.

Nonetheless, `claro_user.is_enabled` is set to false (0).

Deleting them from the admin interface does not change anything (table row is removed but the user is still there when you refresh the page). And data are identical before and after this new deletion.

**Comment by ngodfraind** [comment]
This does not make any sense for.
Here is how the results are retrieved:
=> UserManager::getAllUsers()
=> UserRepository::findAll()
This method is fired with the executeQuery set to false (because of the pager).
It has the WHERE isEnabled = true condition.

Am I wrong

**Comment by ChMat** [comment]
When no search is activated, you are right: disabled users are not shown.

But as soon as there is a search criteria, you end up in `UserRepository::findByName()` and I see a precedence issue between AND and OR (AND has a higher precedence).
