### ISSUE TITLE
/tmp directory submerged with zip files

### ISSUE THREAD

**Issue by ChMat** [claroline/CoreBundle#1383]
It looks like students like to download resources as zip files. Our production server /tmp directory is literally drowned in zip files.

We have set up a purge script but it was taken over by more than he could handle.

Is there anything in place to prevent this?

**Comment by ngodfraind** [comment]
I have no idea how to fix this properly. We create an archive, then we serve it to the client with a symfony2 response and the script end before we can clean anything.

The code is located in the ResouceController:download method. From then it is pretty easy to follow. I'll look at it tomorrow but I'm not sure if I can change it.

**Comment by ChMat** [comment]
For those wondering, here is how we solved the issue at the server level. We created a cron task running every hour that deletes zip files older than 120 minutes.

``` bash
    #!/bin/bash
    
    for i in `find /tmp -mmin +120 -type f | grep -E '[a-zA-Z0-9]{8}-([a-zA-Z0-9]{4}-){3}[a-zA-Z0-9]{12}\.zip'`;
    do 
         rm -f $i;
    done
```

Maybe this kind of command could be migrated into a CoreBundle command? Or the download log could serve as a reference for files to delete by adding the full path to zip files that were generated by the server?

**Comment by ngodfraind** [comment]
It depends on how we want to solve this issue. I'll talk about it at our dev meeting tomorrow. From then I'll pick a solution and implement it.

A command that cleans the tmp/ directory looks nice.  Note that in the app/config folder, there is a tmp_file file. This file contains the list of file we put in the directory folder but the list may be incomplete.

Also, if something goes wrong, the file may not be added here so I'm not sure we should keep it.

**Comment by ngodfraind** [comment]
I remembered we did a cron on our server wich simply goes wild and runs 'rm -rf /tmp/*'.
It also cleans php-fpm log and tmp files. I'll add a note on the readme wich will explain how to do it.
