### ISSUE TITLE
Remove path_mode and related functions

### ISSUE THREAD

**Issue by stefk** [claroline/CoreBundle#346]
Provided the css/js method is fully working.

**Comment by ngodfraind** [comment]
Is it still a problem ?
What do you mean ?

**Comment by stefk** [comment]
I think it's related to the way resources were included in iframes in earlier versions of activities. A special query parameter was appended to urls in case the resource was embedded. Or something like that... I don't remember exactly.

Anyway the implementation has changed and `path_mode` doesn't seem to have any use now. Yet if you look for it, you'll find a few references left (e.g. *Twig/ResourceModeExtension*).

**Comment by ngodfraind** [comment]
Done.
