### ISSUE TITLE
TinyMce ressource Picker - prompt to set public access rights

### ISSUE THREAD

**Issue by bradInside** [claroline/CoreBundle#520]
this is just a suggestion,

I was asking the possibility to have something like a prompt when you try to insert a resource from your workspace via the resource picker of tiny MCE that could  ask you if you want to change the access right of your ressource.

because right now , for example in evaluation,  if you link some resources from your workspace via the richText of Tiny mce, others people will not be able to see them if they have not the correct rights.

I understand why , but if i use it like a lambda user ,  i'lll have to go in my workspace and change right of each resource before insert them, i think this will be boring.

**Comment by ngodfraind** [comment]
The 'public document' folder soves this issue.
