### ISSUE TITLE
Workspace setGuid

### ISSUE THREAD

**Issue by vVYou** [claroline/CoreBundle#521]
Un problème survient si l'on utilise la methode setGuid d'un workspace.

Le guid du workspace est correctement édité, mais le champ name des claro_role n'est pas mis à jour, il contient toujours l'ancien guid du workspace.
Cela provoque donc des soucis lorsque l'on affiche l'ensemble des workspaces de l'utilisateur ou lorsque l'on veut accéder au workspace dont le guid a été modifié.

**Comment by ngodfraind** [comment]
This issue is now irrelevant.
