### ISSUE TITLE
TinyMce Uploaded Resources and Rights

### ISSUE THREAD

**Issue by bradInside** [claroline/CoreBundle#542]
I don't know if i do something wrong or if its a bug.

First, i log as admin,
I have a workspace called 'work'. In this one, i have made an evaluation.
In Evaluation edition you can for example fill the instructions with a TinyMce.
I write some text and upload an image.

The image is in fact uploaded not in the 'work' workspace but in my personal workspace with private rights. So i go back to my personal workspace and change the right on the picture to 'utilisateurs de la plateforme' .

With another account ( not and admin account) ,  ( loggued) , i go in the 'work' workspace and  i open evaluation, i see the instruction but the image is not loaded.

I can't see the uploaded image until the rights are changed to 'aux utilisateurs anonymes'.

**Comment by ngodfraind** [comment]
That was fixed a long time ago.
