### ISSUE TITLE
Change default value of event priority to "normal" by default in agenda modal

### ISSUE THREAD

**Issue by ericvincenterv** [claroline/CoreBundle#595]
The default priority for events in the agenda modal is not set 
If you set the priority to any value, you are stuck with a priority. 
You can no longer remove the priority when editing the event.

Either the event should have a default value of "Normal" or we should add a "No priority" value to the select.

![priority](https://cloud.githubusercontent.com/assets/5363344/2944544/e4ab8484-d9d4-11e3-9815-3f092e400464.png)

We have tried to add a default value to the entity via a constructor and tried to fiddle with the AgendaType form builder but can not seem to change the default value.

**Comment by ngodfraind** [comment]
The agenda will be removed and reworked soon.
