### ISSUE TITLE
Agenda - All day event & Task improvement

### ISSUE THREAD

**Issue by pitrackster** [claroline/CoreBundle#917]
Hi there !

While working on the ability to create "All day events" I saw one strange thing which is the use of a field named ```allDay``` to set an event as a task. 
From my opinion it leads to misunderstanding and poor task features (a task has no due date information, we can't know if it's done or not...). 

Is there any reason to do things this way ?

If you are ok we propose to : 

- Firstly remove all Task reference in Event entity / form / type etc. and calendar.js and use the allDay field to what it means -> the creation of an all day event 
- Secondly create a Task entity (with at least dueDate and isDone informations) with it's own form / type / controller ...
- The task layout will stay the same and will be shown in the same place

What do you think about it ?

Thanks !

**Comment by ngodfraind** [comment]
This was changed not so long ago. 'Task' and 'allDay' are separate options.
